### ISSUE TITLE
Connecting to Trello without poping up a authorization window

### ISSUE THREAD

**Issue by rappol** [t1mmen/opauth-trello#1]
Hi there,
is it possible to connect to Trello without poping up a authorization window?

Because im doing a server side app which works like Zapier...it connects to Trello and creates cards after someone logins on my site.

In the client.js library that Trello provide there is a parameter which is 

**interactive**
true or false
Default is true
If false, don’t redirect or popup, only use the stored token

**Comment by t1mmen** [comment]
Opauth works server-side using redirects, so this should work as you expect on the server-side.

If I'm misunderstanding your question and you're actually trying to use this plugin but running into issues, please clarify :)

**Comment by rappol** [comment]
Hi @t1mmen  thanks for replying.

Yes im running into issues. I'm able to authenticate to trello (it opens a popup asking for permissions) and i receive the token (it redirects to the callback.php)

But if i use the same url again MY_HOST/OpAuth/master/example/trello  it opens the popup again asking for permission. I think it only should ask one time right? Or im i missing something?

**Comment by rappol** [comment]
Should i save the token in a database and use it with every API Request in the future? (is the token always the same for my app? since is already approved in the trello settings?)

**Comment by t1mmen** [comment]
If I'm understanding you correctly, you'd like it to skip the authorization screen the second time someone connects via Trello (ie, user already authorized your app via Trello, so don't show screen again), correct?

I'm pretty sure Trello's implementation always shows the authorization screen, even if you're authorized the connection previously.

To your last question: Yes, you should be storing the token if you don't want the user to have to authorize every time :)

**Comment by rappol** [comment]
hmm.ok..  

What im trying to accomplished is:

1 - The user fills a form in my site and submit it
2 - In the background i grab the anwsers of the form and connect to my trello account to create a card

It shouldn't ask nothing to the user...since im not acessing his trello, but mine. 

How can i accomplished this?

**Comment by t1mmen** [comment]
You don't need to ask the user to authenticate with Trello, unless you plan on acting on behalf of a user.

Since you'll be using your own credentials, try using your opauth-trello implementation and sign in as yourself. Make a note of the trello api keys, and use those on the backend when you make requests to the trello API.

**Comment by rappol** [comment]
ok nice. One last question though. 

Can i use opauth-trello to make the API calls? Im not sure how to do it. Or is the opauth-trello just for authentication?

**Comment by t1mmen** [comment]
Sorry, no, `opauth-trello` is only for authentication. You'll need to look at Trello API wrappers or SDK's, like http://mattzuba.bitbucket.org/php-trello/ (no experience using that project, but looks like what you're after)

**Comment by rappol** [comment]
Many thanks Timm!!

No dia quarta-feira, 24 de fevereiro de 2016, Timm Stokke <
notifications@github.com> escreveu:

> Sorry, no, opauth-trello is only for authentication. You'll need to look
> at Trello API wrappers or SDK's, like
> http://mattzuba.bitbucket.org/php-trello/ (no experience using that
> project, but looks like what you're after)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/t1mmen/opauth-trello/issues/1#issuecomment-187994584.

## 

Cumprimentos,

Hugo Dias

Ao reencaminhar e-mails:
- Remova os endereços de e-mail que aparecem no corpo do texto.
- Para várias pessoas, utilize sempre Cópia Oculta (Cco) ou (Bcc).
